### ISSUE TITLE
Menu: "Produção"

### ISSUE THREAD

**Issue by zampolo** [LAPSHub/hp#4]
Incluir uma opção no menu: "Produção"

**Comment by Leonardo-Soares** [comment]
Esqueci de sinalizar o commit dessa inssue

**Comment by zampolo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [correção do menu](https://trello.com/c/jHry2VnA/88-corre%C3%A7%C3%A3o-do-menu)

**Comment by zampolo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [menu: produção](https://trello.com/c/z4sFiuR7/90-menu-produ%C3%A7%C3%A3o)
